import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./globals.css";

import { ThemeProvider } from "./context/lightdark";

import AuthContext from "./Providers";
import ToasterContext from "./context/Toaster";
// import Provider from "./context/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} dark:bg-black bg-slate-50 dark:text-white`}
      >
        <ThemeProvider>
          <ToasterContext />
          <AuthContext>
            {/* <Provider> */}
            {children}
            {/* </Provider> */}
          </AuthContext>
        </ThemeProvider>
      </body>
    </html>
  );
}
