import { Toaster } from "react-hot-toast";

export const metadata = {
    title: "Next.js",
    description: "Generated by Next.js",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <div className="w-full h-screen ">
            <Toaster />
            {children}
        </div>
    );
}
